### ISSUE TITLE
What kind of metrics works well in "Introducing Metrics in InnerSource"？

### ISSUE THREAD

**Issue by ericshanda** [InnerSourceCommons/InnerSourcePatterns#115]
As we know , metrics just like a product must be sell to different kinds of users including C-level, middle managers and the team members. All of them are concerned about different aspect. So what kind of metrics would work?

**Comment by NewMexicoKid** [comment]
You don't necessarily need the same metrics for the different audiences. C-level leaders will want to know about the health and growth of the inner source program, so the metrics will tend to be ones that represent this in an aggregate sense. Middle managers will want to know how their people are doing in the program along the different dimensions (e.g., quality, activity) or how much the components they own are being reused or contributed to. Engineers will want to know how they are being tracked and measured; the metrics at this level will need to change over time to avoid gamification and should be introduced with caution to be careful of unintended consequences.

**Comment by rrrutledge** [comment]
I would only track and measure in aggregate never back to any one person or team to prevent people changing their behavior to look good for the metric.

**Comment by MaineC** [comment]
One thing I found helpful was to follow the goal-question-metric approach to come up with metrics that match the goals of the organisation at hand.

Before rolling out a specific metric for a change think about the goal you want to achieve with the change.

For example:

If you want to use inner source in order to increase cross team collaboration on code projects, that's precisely what you should measure.

That's also why I think asking the question here won't give you the answers you need...

For me personally, I found some of the metrics that https://chaoss.community/ worked on helpful for our internal organisation as well. What you will see though is that your metrics will evolve as the goals of your initiative shift or grow.
