### ISSUE TITLE
Missing patterns related to Common Requirements pattern

### ISSUE THREAD

**Issue by jsmanrique** [InnerSourceCommons/InnerSourcePatterns#386]
Reading the "[Common Requirements](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/patterns/2-structured/common-requirements.md)" pattern I've found there are a couple of patterns mentioned as "pattern to be written", but I haven't found any additional information about them.

The missing patterns seem to be related to the initial and resulting context of the Common Requirements pattern, so I find them quite important to fully understand the pattern itself:

From the pattern Context section:
```text
This pattern applies if there is a Strong Code Owner [pattern to be written] or if there is weak code ownership, 
or no Benevolent Sponsor [pattern to be written].
```

From the Resulting Context section:
```text
A related pattern [pattern to be written] is a circular story-writing exercise reported at one company 
employing InnerSource
```

Wouldn't it be nice to have those patterns drafted?

Where could we look for related information?

**Comment by spier** [comment]
Great catch @jsmanrique!

Based on the [requirements](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/meta/contributor-handbook.md#requirements-level-2---structured) that we are applying on patterns today, this pattern should be in maturity level "Structured". If we were to write this pattern today, we would keep it in "Initial" i.e. we would not publish it to the book until the placeholders are removed.

However I believe that this pattern was written and published at a time before we had such written requirements and review guidelines in place. So in a way it is an artifact from the early days of the InnerSourcePatterns repo :)

I will try to find traces of the patterns that are linked to from the [Common Requirements](https://patterns.innersourcecommons.org/p/common-requirements) pattern. There is an old Google Group that might have some traces but I don't know if it is publicly available.

And I see that you already raised this question in Slack as well, so maybe we can find somebody who has further context from the time at which the pattern was written.

**Comment by spier** [comment]
I found the PR in which this pattern was first created:
https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/11

That PR also contains a mention of "PLoP 2017", which I assume might have been an in-person event of the group at which the pattern was written.

Still looking for more ...

**Comment by spier** [comment]
When we re-orgnized the files in our repo the pattern file `common-requirements.md` was moved (without doing much change to the content itself).

Here history for `common-requirements.md` [before moving the file](https://github.com/InnerSourceCommons/InnerSourcePatterns/commits/82061e3cb02acab3806a512a1fec42c6484765f9/common-requirements.md).

**Comment by spier** [comment]
Actually, after reading the pattern again, I am not quite sure why it is even in **Level 2 - Structured** in the first place.
It doesn't have a "Known Instance", i.e. no organization/company has confirmed that they are using this pattern.

So in theory we should move the pattern back to **Level 1 - Initial**, and with that un-publish the pattern from our book (i.e. the link `https://patterns.innersourcecommons.org/p/common-requirements` would be dead). Note: We have not done this before.

@jsmanrique do you have a case where you might apply this pattern in an organization?

Maybe we can use your experience and the input we got from @dicortazar in Slack to improve this pattern to a point where it is good enough to stay published in our book? I would really love to be able to keep the pattern published in the book (rather than un-publishing it).

**Comment by NewMexicoKid** [comment]
There are some notes in the innersource-commons google group (e.g., [2016-12-07](https://groups.google.com/g/innersource-commons/c/iK6N-XKfWFY/m/hTocqfzxDAAJ) and [2017-07-18](https://groups.google.com/g/innersource-commons/c/YzkzqF-h50w/m/lp1eCQBgAgAJ)). 

Common Requirements was primarily authored by Bob Hanmer; although it was unstated directly in the pattern, I believe this was based on his experiences and could probably be treated as a known instance that can't be explicitly stated. E.g., Large telecom provider.

The pattern was officially reviewed at PLoP 17 (and is [available](https://hillside.net/plop/2017/papers/proceedings/papers/24-bank.pdf) in the [conference proceedings](https://hillside.net/plop/2017/papers/proceedings/)).

**Comment by spier** [comment]
@NewMexicoKid to the rescue! 
Thanks for the pointers, we will check those out.

Do you have any other recollection of these to-be-written patterns that the pattern points to?

Quoting directly from [Common Requirements](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/patterns/2-structured/common-requirements.md):

- `Strong Code Owner [pattern to be written]`
- `Benevolent Sponsor [pattern to be written]` 
- `[pattern to be written] is a circular story-writing exercise`

Thanks again for your help here. It is invaluable!

**Comment by NewMexicoKid** [comment]
My only memory of the discussion was from the notes (which largely are stated in the pattern). A Strong Code Owner is a pattern where all changes to a shared repository have to be approved by the repo owner (vs. Weak code ownership where no one really owns the code).

The circular story writing exercise is also described pretty fully in the pattern: 
*A related pattern (to be written) is a circular story-writing exercise reported at one company employing Inner Sourcing.  
The developers write a story to solve a problem in one way.*

*The program managers rewrite the story to better express their needs---keeping the essence the same. By the time it returns to developers though they don't recognize it as what they wanted to do in the first place and so balk at implementing it.  The solution to this pattern is to have more seats around the planning table so that story modifications are understood across the project not just in the developer or program manager camps.*

I am guessing that Benevolent Sponsor (in the context of how you might solve or address the problem of Common Requirements/shared repo) is about an organization or exec that provides resources to organize the inner sourcing project, essentially taking *de facto* ownership of this common code.

**Comment by spier** [comment]
Great extra info. Thanks Tim!

I will try to remove the placeholders in the pattern, by working in some of this info.
Hope I don't change the intended meaning of the pattern.

Btw do you know if the original author of the pattern might still be available for doing a review of the changes we are making?

**Comment by jsmanrique** [comment]
Thank you @NewMexicoKid !

I like the approach you propose @spier

**Comment by spier** [comment]
As the placeholders were inserted in the pattern many years long ago, we have not easy way of writing those missing patterns.
Therefore we opted to replacing the placeholders with more description of the respective points inline in the pattern. See #388 

With that I am closing this issue but by all means open a new one if you find more issues with this pattern.
Thanks for your help!
