### ISSUE TITLE
Improve the Japanese translation of InnerSource Patterns

### ISSUE THREAD

**Issue by yuhattor** [InnerSourceCommons/InnerSourcePatterns#434]
Japanese Translation of InnerSource Patterns is in the early phases. InnerSource Commons Japan has adopted textlint, including unifying Japanese notation and improving readability, and discussions are being held by volunteer members. When the Japanese translation has been completed to some extent, we will improve the Japanese of InnerSource Patterns by referring to the TRANSLATION-POLICY and textlint in the following repository.
https://github.com/InnerSourceCommons/japanese-contents

**Comment by spier** [comment]
I am not 100% clear what improvements this issue is describing. 

Trying to summarize what I understood from this issue:

* link from [InnerSourcePatterns/../translation/README.md](https://github.com/InnerSourceCommons/InnerSourcePatterns/tree/main/translation) to [japanese-contents/TRANSLATION-POLICY.md](https://github.com/InnerSourceCommons/japanese-contents/blob/main/TRANSLATION-POLICY.md)
* apply [japanese-contents/../textlint](https://github.com/InnerSourceCommons/japanese-contents/tree/main/textlint) in the InnerSourcePatterns repo as well? (I don't know textlint. is it similar to markdownlint? would it make sense to adopt it for the whole InnerSourcePatterns, or just for the japanese translation?)

If you could help clarify this, that would be great.

**Comment by yuhattor** [comment]
We are currently working on standardizing the Japanese notation. And [textlint](https://github.com/textlint/textlint) is lint tool for natural languages. For instance, this tool is helpful when you don't want the words "center" and "center" mixed together in one document.

This issue was created as a task to improve the Japanese translation based on the rules created by the Japanese community, so it is not intended to go so far as to put a specific lint into the CI/CD pipeline. For the time being, I plan to run textlint on the cli. I think textlint is a very good tool, maybe we could implement it in the InnerSource Patterns pipeline someday

**Comment by spier** [comment]
Sounds interesting. I would like to see textlint in action :) 

If I don't get to try it out myself, maybe you could do a little demo at some point?

**Comment by yuhattor** [comment]
For the record, I will do work on the [jp-translation-improvement](https://github.com/InnerSourceCommons/InnerSourcePatterns/tree/jp-translation-improvement) branch. The branch name like book-jp-improvement might be suitable for management, but it looks that `.github/workflows/book.yml` triggers the GH Actions and update .gitbook.yaml because the branch name starts with "book-jp" 👍

**Comment by spier** [comment]
I think that the GHA only sets the language to JP during the build  if the branch name is exactly "book-jp". So we should change that to also work for branches starting with "book-jp". 

Feel free to try that out. 

I currently have some issues with my laptop so can only contribute from Mobile ;)

> For the record, I will do work on the [jp-translation-improvement](https://github.com/InnerSourceCommons/InnerSourcePatterns/tree/jp-translation-improvement) branch. The branch name like book-jp-improvement might be suitable for management, but it looks that `.github/workflows/book.yml` triggers the GH Actions and update .gitbook.yaml because the branch name starts with "book-jp" 👍

**Comment by yuhattor** [comment]
We fixed the most important TC part. This is an ongoing work, but I will close it once we have completed the major corrections.
